### ISSUE TITLE
[Antd] Select can not work with mode='tags'

### ISSUE THREAD

**Issue by nvlong198** [xrutayisire/react-js-cron#2]
Select can not work with mode='tags', become mode='multiple' when using with  react-js-cron

playground: https://stackblitz.com/edit/react-mdwfya?file=index.js

**Comment by nvlong198** [comment]
@xrutayisire problem is in `components/CustomSelect`

what actually `element.setAttribute('readonly', 'readonly')` do ?

```js
useEffect(() => {
    Array.from(
      document.getElementsByClassName('ant-select-selection-search-input')
    ).forEach((element: Element) => {
      element.setAttribute('readonly', 'readonly')
    })
  }, [])
```

**Comment by xrutayisire** [comment]
Hey, 

Thanks for the report!

I see the problem, I will provide a fix 👍 

```js
useEffect(() => {
    Array.from(
      document.getElementsByClassName('ant-select-selection-search-input')
    ).forEach((element: Element) => {
      element.setAttribute('readonly', 'readonly')
    })
  }, [])
```

This code is used to disabled hidden search input of antd that cause problems because we don't want any  search field on it.

**Comment by nvlong198** [comment]
Any problems if change mode to `'multiple'`?
 
```js
<Select
      mode='multiple'
      allowClear={!readOnly}
.... />
```

**Comment by xrutayisire** [comment]
As you can see on the following screenshot, it not wanted to let the user type anything in the search input:

<img width="201" alt="Screenshot 2020-11-12 at 13 50 21" src="https://user-images.githubusercontent.com/19946868/98942389-32ead800-24ee-11eb-8796-caac6fe8ed3f.png">

And Design provide a "showSearch" property but it's not working with the "tags" mode 😕

**Comment by xrutayisire** [comment]
I heavily use the prop "tagRender" from antd so that's why I used "tags" mode.

I just checked antd documentation and then RcSelect documentation about "tagRender" and they added unit tests and examples only with "tags" mode.

BUT the doc don't talk about the "mode" (yet)
> tagRender | Customize tag render | (props) => ReactNode 

BUT again, it's currently working with "multiple" as you point out...  
In their code they don't test the mode https://github.com/react-component/select/blob/05d19a953315f4ecd5510dbc6d4bd5230ccff6e5/src/Selector/MultipleSelector.tsx#L145 .

Let me check If I find out mode about the use of "tagRender" with "multiple" 🙂
> If you have any indication I'm open for it!

**Comment by xrutayisire** [comment]
Ok, it seems to be ok to use it with "multiple". 🥳 
For me, they should have named it differently because of the explicit mode "tags".

Anyway to give you info about it:

- Original issue asking for a renderTag function: https://github.com/ant-design/ant-design/issues/12910
- PR on RcSelect: https://github.com/react-component/select/pull/445
- PR on antd Select: https://github.com/ant-design/ant-design/pull/21064

And as you can see here (https://github.com/ant-design/ant-design/pull/21064#discussion_r377512373) they even discussed it with "multiple" mode and updated the demo: https://github.com/ant-design/ant-design/blob/master/components/select/demo/custom-tag-render.md#en-us

So good for me, let me change that, check if everything work fine and I can will release a new hotfix of "react-js-cron".

**Comment by xrutayisire** [comment]
It's live 🥳

New version 1.1.1: https://www.npmjs.com/package/react-js-cron

Try it and let me know but you should not have any problem now 🙂

I forked your example to show you the fix: https://stackblitz.com/edit/react-mdwfya-t1i1wg?file=package.json
