### ISSUE TITLE
Feature to add seconds

### ISSUE THREAD

**Issue by carlosporta** [xrutayisire/react-js-cron#23]
Hello,

Our cron jobs run on a period of less than a minute. Is it possible to add seconds to this library?

Great job!

**Comment by xrutayisire** [comment]
Hello, 

Thanks for the issue!

To simply answer the question, it's because I needed and decided to only support UNIX cron syntax and not Quartz cron syntax.
cf: https://flylib.com/books/en/2.65.1/the_cron_expression_format.html

Seconds is not standard and it's part of the Quartz cron syntax. It could be an improvement of this library if it doesn't add too much complicated code to maintain.

As I don't need to support Quartz syntax, I may not develop this right away so feel free for a PR 🙂
