### ISSUE TITLE
Minimal interval

### ISSUE THREAD

**Issue by dana93os** [xrutayisire/react-js-cron#25]
We're using your library and sometimes we want to disable selecting the "every minute" interval or set some kind of minimal interval.

**Comment by xrutayisire** [comment]
Hello,

Thanks for using this library!

Without any modification you can already do something like this. 

- Displaying an error when every minute is selected, and you can use this error to disable a form submit for example.
Example: [https://codesandbox.io/s/react-js-cron-minimal-interval-forked-cciq5k?file=/src/App.tsx](https://codesandbox.io/s/react-js-cron-minimal-interval-forked-cciq5k?file=/src/App.tsx)

**Comment by dana93os** [comment]
Wow, perfect! Thank you for developing it! Any way to contribute financially?

**Comment by xrutayisire** [comment]
Thanks for the support!! I currently don't have a donation system in place, but I could think about it If you want to support this library 😃 

I agree with you that it can be a new feature. I have some questions to think about it:

- Removing the "minutes" option of the first dropdown will still allow the user to select every minute since when deselecting all values, every minute is set anyway, how to handle the last deselection that trigger the every minute to happen? (block it?) 
- To do something more generic, it's not only "every minute" that need to be disabled but any other value right?
 
 Let me know If my questions are not clear enough

**Comment by dana93os** [comment]
You are right. Maybe this is not the library problem.

Will explain more about what we do, maybe it will be helpful for you to understand me.

We wanted to limit our clients of running tasks every minute or even every hour. So we added this rule to check:
`
    const items = value.split(' ');

    if (value === '* * * * *' || items[1] === '*') {
      setError('The interval is too small');
    } else {
      setError(null);
    }
`

Yes, it will be possible to run almost every hour (23/24) if some user will really want it and select all 23 hours, but it's okay at least for now.

Thanks, for your help and support! Maybe the library is not so big but it's working well!
