### ISSUE TITLE
Locale for UNITS alt

### ISSUE THREAD

**Issue by Dalion** [xrutayisire/react-js-cron#3]
Hello! Thanks for this great library, it's helped me a lot! But I faced a little problem. 

I'd like to use `locale` prop with `humanizeLabels` and I can't override these labels.

Is there any way to use custom localisation for `months` and `week-days` constants `alt` values?
May be You can add this feature?

**Comment by xrutayisire** [comment]
Hi, 

I'm happy people can use this library!

Oh, yes it's true, it's because I wanted to keep a valid Cron syntax for the ALT values. (cf: https://en.wikipedia.org/wiki/Cron#CRON_expression)

But you want to humanize labels with a translation system only right? And not the value?

So I will provide a way to translate the labels when using "humanizeLabels", but values will not be translated when using "humanizeValue".
The value will always be a valid Cron syntax but what is displayed inside the dropdown can be translated.

Is this way good for you?

**Comment by xrutayisire** [comment]
Didn't wait for your answer 😉

I just released a new version v1.2.0 with the possibility to translate alternative labels 🥳

There are two new properties for the "locale" object: "altWeekDays" and "altMonths".
> Don't forget that the order is important for these properties too

Go check out the story with the French example: https://xrutayisire.github.io/react-js-cron/?path=/docs/reactjs-cron--french-locale 
Don't hesitate to tell me if you find a problem with the new release.

If it's good for you, let me know, so I can close the issue 😉

**Comment by Dalion** [comment]
Oh, excellent! 

Yep, of course it's enough to translate only labels. 

Thank You very much for such fast response and new version!
