### ISSUE TITLE
Why not support seconds

### ISSUE THREAD

**Issue by yingpengsha** [xrutayisire/react-js-cron#4]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need seconds Selector. (hahaha

**Describe the solution you'd like**
Add seconds Selector

**Describe alternatives you've considered**
Unless there's a better component or I write another component on top of yours

**Additional context**
I'll try to submit my code, maybe not right away, maybe just give up.

**Comment by xrutayisire** [comment]
Hi,

Thanks for the issue! 

To simply answer the question, it's because I needed and decided to only support UNIX cron syntax and not Quartz cron syntax.
cf: https://flylib.com/books/en/2.65.1/the_cron_expression_format.html

Seconds is not standard and it's part of the Quartz cron syntax. It could be an improvement of this library if it doesn't add too much complicated code to maintain.

I will think about it, to see how it can be done without breaking all the current system.

As I don't need to support Quartz syntax, I may not develop this right away so feel free for a PR 🙂
