### ISSUE TITLE
Uncaught ReferenceError: moment is not defined

### ISSUE THREAD

**Issue by tgb20** [xrutayisire/react-js-cron#5]
**Describe the bug**
Upon opening page containing Cron with antd and react installed in my project I get the error `Uncaught ReferenceError: moment is not defined`

**To Reproduce**
Install antd `yarn add antd`
Install react-js-cron `yarn add react-js-cron`

Serve project

I have added Cron for testing using
```javascript
<Cron value='30 5 * * 1,6' setValue={(e: string) => { console.log(e); }} />
```

Without that Cron tag the page can load fine.

**Comment by xrutayisire** [comment]
Hi, 

Thanks for the issue, please create a CodeSandbox with the bug so I can reproduce.

It's really strange because the Cron component don't have any dependencies except React and antd, so moment is not used at all.

Are you sure you are not using moment when using the Cron component on your side?

**Comment by xrutayisire** [comment]
Could you please provide a reproducible example, I just created a CodeSandbox and there is no crash: https://codesandbox.io/s/epic-mcnulty-wnfsx

I think you may have some code relative to "moment" library on your side, no?

**Comment by tgb20** [comment]
My project does use moment. I have identified that the source of the issue comes from antd. When installing antd it also has moment as a dependency. The issue is even when I force it to use the version of moment I am using in the rest of my project the act of having antd breaks moment.

**Comment by xrutayisire** [comment]
I just added "moment" to the CodeSandbox (https://codesandbox.io/s/epic-mcnulty-wnfsx) and it seems to work pretty fine with it.

Maybe it's how you are handling the build process? Anyway I don't think the problem is coming from this library.
Is it breaking when you want to add some other component from antd? 

If you add the "Select" component from antd in your app, do you have the same problem?

**Comment by tgb20** [comment]
It seems any antd component causes the issue to occur.

**Comment by xrutayisire** [comment]
😕 Hum, it could be the way you are handling your build or something on your side.

Since it's not coming from "react-js-cron" I will close this issue here, but I would be happy to help you if you create a stack overflow with your problem with antd. Don't hesitate to comment here with the link 🙂

**Comment by tgb20** [comment]
Thanks for the offer, I actually just fixed it reading through the build files. We cull parts of packages that we are not actively using to reduce the overall size, moment was in that list. Facepalm.
