### ISSUE TITLE
It's possible to add timezone?

### ISSUE THREAD

**Issue by Sakthivelgovindan** [xrutayisire/react-js-cron#59]
I want to include timezone, it's possible to?

**Comment by xrutayisire** [comment]
The current Cron component output a simple string as value and is not related to any timezone and will work for all cases.
Working with a timezone means you have to set up an env variable for that on Linux, for example.
See: https://linuxhint.com/set-timezone-crontab/

I prefer to keep this component simple and only output a string since the selection of the timezone is on your side, a simple Select with the different timezones you want to support. No need to make this component more complex for that.

I hope you will succeed to do the timezone on your end 🙂
