### ISSUE TITLE
German Locale addition

### ISSUE THREAD

**Issue by janBock** [xrutayisire/react-js-cron#65]
**Describe / Is your feature request related to a problem? Please describe.**
My request is regarding extending the Locale option to include German, similar to how French exists

I have both English and German in my i18n translations, and am keen to have this built into the dropdowns and built-in texts in German, similar to the implementation that exists for French.

**Comment by xrutayisire** [comment]
Hey,

French locale don't really exist. I made this library so you can integrate with any locale you want.

There is only the DEFAULT_LOCALE_EN that is used internally, but the API is made to extend with every locale. The Storybook give an example because I'm French, but it's not an integrated locale.

You can just do as in the Storybook:

```ts
const GERMAN_LOCALE: Locale = {
  <write here your germal locale>
}

<Cron
  locale={GERMAN_LOCALE}
  value={values.cronValue}
  setValue={(newValue: string) => {
    dispatchValues({
      type: 'set_values',
      value: newValue,
    })
  }}
  onError={onError}
/>
```

**Comment by janBock** [comment]
Righttt, okay thanks for clarifying. So the translated values would need to be defined like youve done for the french locale in src/stories/constants.stories.ts
